workflows:
  triangle-workflow:
    name: Triangle App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.3
    publishing:
      email:
        recipients:
          - aaronevanjulio18@gmail.com
        notify:
          success: true
          failure: true